export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS'
export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS'
export const PUT_CLIENT_SUCCESS = 'PUT_CLIENT_SUCCESS'
export const DEL_CLIENT_SUCCESS = 'DEL_CLIENT_SUCCESS'

export const GET_HOTELS_SUCCESS = 'GET_HOTELS_SUCCESS'
export const ADD_HOTEL_SUCCESS = 'ADD_HOTEL_SUCCESS'
export const PUT_HOTEL_SUCCESS = 'PUT_HOTEL_SUCCESS'
export const DEL_HOTEL_SUCCESS = 'DEL_HOTEL_SUCCESS'

export const GET_TOURS_SUCCESS = 'GET_TOURS_SUCCESS'
export const ADD_TOUR_SUCCESS = 'ADD_TOUR_SUCCESS'
export const PUT_TOUR_SUCCESS = 'PUT_TOUR_SUCCESS'
export const DEL_TOUR_SUCCESS = 'DEL_TOUR_SUCCES'

export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS'
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS'
export const DEL_ORDER_SUCCESS = 'DEL_ORDER_SUCCESS'
